public class Ejercicio2 {

    /*Secuencia fibonacci*/
    /**
     * Each new term in the Fibonacci sequence is generated by adding the previous two terms.
     * By starting with $1$ and 2, the first 10 terms will be:
     * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89...
     *  By considering the terms in the Fibonacci sequence whose values do not
     *  exceed four million, find the sum of the even-valued terms
     */


    public static void main(String[] args) {

        int numero1 = 0;
        int numero2 = 1;
        int suma = 0;
        int numerolimite = 4000000;

        System.out.println("Secuencia de Fibonacci:");

        for (int i = 1; numero1<numerolimite; i++) {
            System.out.println(numero1 + " ");

            if (numero1 % 2 == 0) {
                suma += numero1;
            }

            int sumaFibonacci = numero1 + numero2;
            numero1 = numero2;
            numero2 = sumaFibonacci;
        }

        System.out.println("La suma  es: " + suma);
    }
}

